import {
  ArrowLeftIcon,
  ArrowRightIcon,
  CaretSortIcon,
  CheckCircledIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CopyIcon,
  Cross2Icon,
  DashboardIcon,
  DotFilledIcon,
  DotsHorizontalIcon,
  DotsVerticalIcon,
  ExitIcon,
  EyeNoneIcon,
  EyeOpenIcon,
  GearIcon,
  ImageIcon,
  MagnifyingGlassIcon,
  MinusIcon,
  PlusIcon,
  TrashIcon,
} from '@radix-ui/react-icons';
import { CircleUserRoundIcon, DollarSignIcon, Loader2Icon, ShoppingCartIcon } from 'lucide-react';
import { BsStar, BsStarFill, BsStarHalf } from 'react-icons/bs';
import { FaFacebook, FaInstagram, FaLinkedin } from 'react-icons/fa';
import { FaGoogle, FaXTwitter } from 'react-icons/fa6';
import { RiMailSendLine } from 'react-icons/ri';

export const Icons = {
  arrowLeft: ArrowLeftIcon,
  arrowRight: ArrowRightIcon,
  caretSort: CaretSortIcon,
  checkCircle: CheckCircledIcon,
  check: CheckIcon,
  chevronDown: ChevronDownIcon,
  chevronLeft: ChevronLeftIcon,
  chevronRight: ChevronRightIcon,
  chevronUp: ChevronUpIcon,
  copy: CopyIcon,
  cross: Cross2Icon,
  dashboard: DashboardIcon,
  dot: DotFilledIcon,
  dotsHorizontal: DotsHorizontalIcon,
  dotsVertical: DotsVerticalIcon,
  logout: ExitIcon,
  eyeNone: EyeNoneIcon,
  eyeOpen: EyeOpenIcon,
  settings: GearIcon,
  placeholder: ImageIcon,
  search: MagnifyingGlassIcon,
  minus: MinusIcon,
  plus: PlusIcon,
  trash: TrashIcon,
  account: CircleUserRoundIcon,
  dollar: DollarSignIcon,
  spinner: Loader2Icon,
  cart: ShoppingCartIcon,
  star: BsStar,
  starFill: BsStarFill,
  starHalf: BsStarHalf,
  facebook: FaFacebook,
  instagram: FaInstagram,
  linkedin: FaLinkedin,
  google: FaGoogle,
  twitter: FaXTwitter,
  mailSend: RiMailSendLine,
};
